### ISSUE TITLE
Add a requirements.txt file

### ISSUE THREAD

**Issue by Naereen** [pcotret/isbn2markdown#1]
It would help to know the requirements of this tool.
Only [`isbntools.app`](https://pypi.python.org/pypi/isbntools) I guess ?

A [`requirements.txt`](https://pip.pypa.io/en/latest/user_guide/#requirements-files) file could help.

**Comment by pcotret** [comment]
Packages needed are written in the Latex file. You should compile it first.
But, yes, I'll write everything in the README.md later today/tonight. Simpler if you don't have Latex installed.
